# Generated by Django 4.2.20 on 2025-04-27 18:14

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(max_length=255, storage=storages.backends.s3.S3Storage(), upload_to='user_images/'),
        ),
    ]
